services:
  - type: web
    name: eduguide-ai-backend
    env: python
    pythonVersion: 3.12.4
    region: oregon
    branch: main
    plan: free

    rootDir: backend

    buildCommand: mkdir -p /tmp/cargo && export CARGO_HOME=/tmp/cargo && pip install -r requirements.txt

    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: GROQ_API_KEY
        sync: false

      - key: GROQ_MODEL
        value: llama-3.3-70b-versatile

      - key: ENABLE_VECTOR_STORE
        value: "false"

      - key: COLLEGE_DATA_PATH
        value: ./data/College_data.csv

      - key: CHROMA_PERSIST_DIR
        value: ./storage/chroma

      - key: FRONTEND_ORIGIN
        sync: false